config/routes.rb
Rails.application.routes.draw do
  root to: 'orders#index'
  resources :orders
  resources :customers
  get 'owners/index'

  get 'owner/index'

   # for all routes, we can use this single line or routes down bellow
  resources :owners
  get '/pages', to: 'pages#index'
  get '/pages/new', to: 'pages#new', as:'new_page'
  post 'pages', to: 'pages#create'
  get '/pages/:id', to: 'pages#show', as:'page'
  get '/pages/:id/edit', to: 'pages#edit', as: 'edit_page'
  patch '/pages/:id/', to:'pages#update'
  delete '/pages/:id', to: 'pages#destroy'
 
  #instead of repeating '/posts/:post_id/comments',  can do following instead
  resources :posts do
  resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  validates_presence_of :customer
  validates :product_name, presence: true
  validates :product_name, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters"}
  validates :product_count, presence: true
  validates :product_count, numericality: { other_than: 0 }
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found

  before_action :set_order, only: [:show, :edit, :update, :destroy]
  layout 'order_layout'


  def index
    @orders = Order.all
  end

  def show
  end


  def new
    @order = Order.new
  end

  
  def edit
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      flash.notice = "The order record was created successfully."
      redirect_to @order
    else
      flash.now.alert = @order.errors.full_messages.to_sentence
      render :new  
    end
  end

  def update
    if @order.update(order_params)
      flash.notice = "The order record was updated successfully."
      redirect_to @order
    else
      flash.now.alert = @order.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'The order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:product_name, :product_count, :customer_id)
    end

    def catch_not_found(e) 
      Rails.logger.debug("We had a not found exception.") # writes an entry to the Rails log
      flash.alert = e.to_s # takes the message from the exception and stores it in the flash object so that it can be displayed to the user
      redirect_to orders_path # puts up the index page again, so that the user does not see that other error page.
    end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for [@customer, order] do |f| %>
  
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    
  <% end %>
  <div class="field">
    <%= f.label :product_name %>
    <%= f.text_field :product_name %>
  </div>

  <div class="field">
    <%= f.label :product_count %>
    <%= f.text_field :product_count %>
  </div>
   <div class="field">
    <%= f.label  :full_name %>
    <%= f.collection_select :customer_id, Customer.all, :id, :full_name, include_blank: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

  

app/views/orders/edit.html.erb
<%= render 'form', order: @order %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>



<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Product name </th>
      <th>Product count </th>
      <th>Ordered by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.product_name %></td>
        <td><%= order.product_count %></td>
        <td><%= order.customer.full_name %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New order', new_order_path %>

app/views/orders/new.html.erb
<%= render 'form', order:@order %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>
<h3>Product name:</h3>
<p><%= @order.product_name %><p>
<h3>Product count:</h3>
<p><%= @order.product_count %></p>
<h3>Ordered by:</h3>
<p><%= @order.customer.full_name %></p>

<button><%= link_to 'Edit', edit_order_path(@order) %></button>
<button><%= link_to 'Delete', @order, method: :delete %></button>
<button><%= link_to 'Back', orders_path %></button>