config/routes.rb
Rails.application.routes.draw do
  root to: 'orders#index'
  resources :orders
  resources :customers
  get 'owners/index'

  get 'owner/index'

   # for all routes, we can use this single line or routes down bellow
  resources :owners
  get '/pages', to: 'pages#index'
  get '/pages/new', to: 'pages#new', as:'new_page'
  post 'pages', to: 'pages#create'
  get '/pages/:id', to: 'pages#show', as:'page'
  get '/pages/:id/edit', to: 'pages#edit', as: 'edit_page'
  patch '/pages/:id/', to:'pages#update'
  delete '/pages/:id', to: 'pages#destroy'
 
  #instead of repeating '/posts/:post_id/comments',  can do following instead
  resources :posts do
  resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :orders
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :phone,  presence: true
    validates :phone, numericality: { only_integer: true }
    validates :phone, length: { is: 10}
    validates :email, presence: true
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i


    def full_name
    "#{first_name} #{last_name}"
    end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  validates_presence_of :customer
  validates :product_name, presence: true
  validates :product_name, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters"}
  validates :product_count, presence: true
  validates :product_count, numericality: { other_than: 0 }
  
end

app/models/owner.rb
class Owner < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.create(comment_params)
    redirect_to @post
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to @post
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @post
  end

  private
  def comment_params
    params.require(:comment).permit(:name, :content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found

  before_action :set_order, only: [:show, :edit, :update, :destroy]
  layout 'order_layout'


  def index
    @orders = Order.all
  end

  def show
  end


  def new
    @order = Order.new
  end

  
  def edit
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      flash.notice = "The order record was created successfully."
      redirect_to @order
    else
      flash.now.alert = @order.errors.full_messages.to_sentence
      render :new  
    end
  end

  def update
    if @order.update(order_params)
      flash.notice = "The order record was updated successfully."
      redirect_to @order
    else
      flash.now.alert = @order.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'The order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:product_name, :product_count, :customer_id)
    end

    def catch_not_found(e) 
      Rails.logger.debug("We had a not found exception.") # writes an entry to the Rails log
      flash.alert = e.to_s # takes the message from the exception and stores it in the flash object so that it can be displayed to the user
      redirect_to orders_path # puts up the index page again, so that the user does not see that other error page.
    end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :set_page, only: [:show, :edit, :update, :destroy]
    def index
        @pages = Page.all
    end
    def show
    end
    def new
        @page = Page.new
    end
    def create
        @page = Page.new(page_params)
        @page.save
        redirect_to @page
        
    end
    def edit

    end
    def update
        @page.update(page_params)
        redirect_to @page
    end
    def destroy
    @page.destroy
    redirect_to pages_path
   end
    private
    def page_params
       params.require(:page).permit(:title, :body, :slug)
    end
    def set_page
        @page = Page.find(params[:id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/owner_helper.rb
module OwnerHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= link_to 'Customers', customers_path %>
  <%= link_to 'Posts', posts_path %>
  <%= link_to 'Orders', orders_path %>
  <%= link_to 'Pages', pages_path %>
    <%= yield %>
    
  </body>
</html>

app/views/layouts/customer_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if !flash[:alert].nil? %>
    <p class="my_alert"><%= flash[:alert] %></p>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/order_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Order</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= link_to 'Customers', customers_path %>
  <%= link_to 'Posts', posts_path %>
  <%= link_to 'Orders', orders_path %>
  <%= link_to 'Pages', pages_path %>
  <% if !flash[:alert].nil? %>
    <p class="my_alert"><%= flash[:alert] %></p>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for(page) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :slug %>
    <%= f.text_field :slug %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<%= render 'form', page: @page %>

app/views/pages/index.html.erb
<h1>Blog Pages</h1>

<% @pages.each do |page| %>
    <p><%= link_to page.title, page %></p>

<% end %>

<p><%= link_to 'New Page', new_page_path %></p>

app/views/pages/new.html.erb
<%= render 'form', page:@page %>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>
<p><%= @page.body %></p>

<%= link_to 'Edit', edit_page_path(@page) %>
<%= link_to 'Delete', @page, method: :delete %>